### ISSUE TITLE
Site, opening blurb - Do we still like it?

### ISSUE THREAD

**Issue by Dawnabelle** [MoravecLabs/ml-site-jekyll#21]
Do you still like this text? Currently, I'm using it directly below the landing. The about section will display the new bio/ML bio we've been working on.

We consider the story that the software needs to tell as well as the story the map is telling.

Software exists all around us. It has become part of our day to day lives. We have apps on our computers, on our phones, on our watches. Even on our glasses. Some software is good and some is not. How do we differentiate between good and not so good software? At Moravec Labs, we believe good software tells a story. It is intuitive. Users don’t need to understand all the aspects of an application to use it.

Maps are similar. They convey a story. The better the map, the more informative the story. Good maps, like good software, should convey meaning and should be easily understood.

That is what makes Software Development with a touch of Maps so interesting. We consider the story that the software needs to tell as well as the story the map is telling. Are the stories the same? Do they complement each other? At Moravec Labs, we weave these stories together to tell a comprehensive and fluid story for the user.

![image](https://user-images.githubusercontent.com/22547262/48097718-7ad41780-e1cf-11e8-8e52-540b6c4bd853.png)

**Resolutions**
The intro blurb has been shortened 

**Resolutions Screen Shot**
![image](https://user-images.githubusercontent.com/22547262/63798632-544aae80-c8bf-11e9-8e82-2b6ad5091682.png)

**Comment by morehavoc** [comment]
@Dawnabelle Here is my refactor... is it too pretentious?


Software is all around us, a part of our everyday lives.  We have apps on our computers, our phones, our watches, and even in some cases, on our glasses.  Much of this software helps us, it makes us better, but some doesn't; software can be used to track our online movements as easily as it can be used to collect data about endangered species.  At Moravec Labs we believe that good software tells a story, is intuitive and helps make the individuals as well as the organization better for using it.  You shouldn't have to suffer with mediocre software.

Maps and data are an important part of the software story.  Good maps, like good software, should convey meaning and be easily understood.  Without data, the software would simply be a black box, a set of instructions with nothing to operate on.  We believe that data and software have to work together to tell the complete story, and to fulfill the promise of software, to make the world better.

That is what makes Software Development with a touch of Maps so interesting. We consider the story that the software needs to tell as well as the story the map is telling. Are the stories the same? Do they complement each other? At Moravec Labs, we weave these stories together to tell a comprehensive and fluid story for the user.

**Comment by morehavoc** [comment]
@Dawnabelle on a semi-related note, should we move the line of "services" above this description?  One thing I just considered is that the text talks about how software is good/bad, etc. but it doesn't actually talk about what it is we do...  maybe we should at something like:

At Moravec Labs, we configure, extend and build custom solutions for clients that are tired of having to change their processes because of software.  We work on hard problems, like:

1. How do we get data from a location where there is no internet?
2. Can technology guarantee data quality and integrity?
3. How can modern tech like chat-bots be infused into everyday processes to make them better?
4. When is more tech bad for the solution?
5. ... maybe some more of these? idk.

**Comment by morehavoc** [comment]
Maybe those should actually match up the icons that you made.

**Comment by Dawnabelle** [comment]
@morehavoc - Slight restructure 
Software is all around us, a part of our lives. Every day we interact with apps on our phones, computers, watches, and even our glasses. Much of this software helps us improve our lives. Unfortunately, some of it does not. Good software tells a story. It is intuitive and makes individuals and organizations better for using it.  At Moravec Labs, we build the software that makes your life, and your business, run smoother.  

Good maps, like good software, should convey meaning and be easily understood. The unlimited narratives revealed with this blend of mapping, data, and good software are what makes software development with a touch of maps so interesting. We consider the story that the software needs to tell as well as the story the map is telling. Are the stories the same? Do they complement each other? At Moravec Labs, we weave these tales together to tell a comprehensive and fluid story for the user. 

Without data, software would simply be a black box, a set of instructions, nothing more.  We believe that data and software must work together to tell the complete story. This fusion allows us to fulfill the promise of software: to make the world a better place. At Moravec Labs, we configure, extend, and build custom solutions for clients who require the most from their software.

**Comment by Dawnabelle** [comment]
@morehavoc I'll think on the services section more too

We work on hard problems, like:

1. How do we get data from a location where there is no internet?
2. Can technology guarantee data quality and integrity?
3. How can modern tech like chat-bots be infused into everyday processes to make them better?
4. When is more tech bad for the solution?
5. ... maybe some more of these? idk.

**Comment by morehavoc** [comment]
@Dawnabelle some updates

Software is all around us, a part of our lives. Every day we interact with apps on our phones, computers, watches, and even our glasses. Good software tells a story. It is intuitive and makes individuals and organizations better for using it. At Moravec Labs, we build the software that makes your life, and your business, run smoother.

Good maps, like good software, should convey meaning and be easily understood. The unlimited narratives revealed with this blend of mapping, data, and good software are what makes software development with a touch of maps so interesting. We consider the story that the software needs to tell as well as the story the map is telling. Are the stories the same? Do they complement each other? At Moravec Labs, we weave these tales together to tell a comprehensive and fluid story for the user.

Without data, software would simply be a set of instructions, nothing more. We believe that data and software must work together to tell the complete story. This fusion allows us to fulfill the promise of software: to make the world a better place. At Moravec Labs, we configure, extend, and build custom solutions for clients who require the most from their software.

**Comment by Dawnabelle** [comment]
Updated
